# Generated by Django 2.1.2 on 2018-10-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20181027_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulante',
            name='contrasenia',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
